
-- -- Table: cars
-- CREATE TABLE IF NOT EXISTS cars (
--   id         SERIAL       NOT NULL PRIMARY KEY,
--   name       VARCHAR(255) NOT NULL,
--   model      VARCHAR(255) NOT NULL,
--   yearFromTo VARCHAR(255) NOT NULL
-- );
--
-- -- Table: catalogs
-- CREATE TABLE IF NOT EXISTS catalogs (
--   id   SERIAL       NOT NULL PRIMARY KEY,
--   name VARCHAR(255) NOT NULL
-- );

-- -- Table: products
-- CREATE TABLE IF NOT EXISTS products (
--   id                  SERIAL       NOT NULL PRIMARY KEY,
--   name                VARCHAR(255) NOT NULL,
--   producer            VARCHAR(255) NOT NULL,
--   productCode         VARCHAR(255) NOT NULL,
--   producerProductCode VARCHAR(255) NOT NULL
-- );
--
-- -- Table for mapping product and cars: product_cars
-- CREATE TABLE IF NOT EXISTS product_cars (
--   product_id INTEGER NOT NULL,
--   car_id     INTEGER NOT NULL,
--   FOREIGN KEY (product_id) REFERENCES products (id),
--   FOREIGN KEY (car_id) REFERENCES cars (id),
--   UNIQUE (product_id, car_id)
-- );
--
-- -- Table for mapping product and catalogs: product_catalogs
-- CREATE TABLE IF NOT EXISTS product_catalogs (
--   product_id INTEGER NOT NULL,
--   catalog_id INTEGER NOT NULL,
--   FOREIGN KEY (product_id) REFERENCES products (id),
--   FOREIGN KEY (catalog_id) REFERENCES catalogs (id),
--   UNIQUE (product_id, catalog_id)
-- );

-- -- Table for mapping product and images: product_images
-- CREATE TABLE IF NOT EXISTS product_images (
--   product_id INTEGER NOT NULL,
--   image_id INTEGER NOT NULL,
--   FOREIGN KEY (product_id) REFERENCES products (id),
--   FOREIGN KEY (image_id) REFERENCES images (id),
--   UNIQUE (product_id, image_id)
-- );


